// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBenN6wz5C_LSs1HMpfleLNkpbTARQa1ss',
    appId: '1:1038411454604:android:8767bdae4487c30da703a9',
    messagingSenderId: '1038411454604',
    projectId: 'fitmate-cf118',
    storageBucket: 'fitmate-cf118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQCYp5mFe07YFhVvIL7SuvIaG7k7L6Mvw',
    appId: '1:1038411454604:ios:8b24b346ea53f4d7a703a9',
    messagingSenderId: '1038411454604',
    projectId: 'fitmate-cf118',
    storageBucket: 'fitmate-cf118.appspot.com',
    androidClientId: '1038411454604-35tkp1arp25pgni9i68dr4g3udv1n3pa.apps.googleusercontent.com',
    iosClientId: '1038411454604-r7pl6bsddrpvtq6o9qfa93bs2ckj2ee2.apps.googleusercontent.com',
    iosBundleId: 'com.examples.fitmate',
  );
}
